version: '3'

networks:
  backend:

services:
  app:
    container_name: transaction-service
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file: .env
    expose:
      - ${PORT}
    ports:
      - ${PORT}:${PORT}
    environment: 
      - MONGODB_URL=mongodb://mongo:27017/transactiondb
      - CLIENT_URL=${CLIENT_URL}
    depends_on:
      - mongo
    networks:
      - backend
  mongo:
    image: mongo
    restart: always
    ports:
      - "27020:27017"
    networks:
      - backend